import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: 'https://mesvantage.com',
  integrations: [
    // applyBaseStyles: false because src/styles/global.css already declares
    // @tailwind base/components/utilities. With both, Astro emitted TWO near-identical
    // stylesheets — 44.7KB of render-blocking CSS per page, each containing its own copy
    // of preflight and its own .bg-navy rule.
    tailwind({ applyBaseStyles: false }),
  ],
  // Sitemap is generated by src/pages/sitemap.xml.ts, not @astrojs/sitemap.
  // See the comment in that file for why.
});
