import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: 'https://mesvantage.com',
  integrations: [tailwind()],
  // Sitemap is generated by src/pages/sitemap.xml.ts, not @astrojs/sitemap.
  // See the comment in that file for why.
});
